# Generated by Django 5.2.5 on 2025-10-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('property_photo', models.ImageField(upload_to='')),
                ('property_category', models.CharField(max_length=100)),
                ('property_name', models.CharField(max_length=100)),
                ('property_location', models.CharField(max_length=100)),
                ('property_budget', models.CharField(max_length=100)),
                ('property_bedroom', models.CharField(max_length=100)),
                ('property_bathroom', models.CharField(max_length=100)),
                ('property_area', models.CharField(max_length=100)),
                ('property_floor', models.CharField(max_length=100)),
                ('property_parking', models.CharField(max_length=100)),
            ],
        ),
    ]
