# Generated by Django 5.2.5 on 2025-10-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('property_name', models.CharField(max_length=100)),
                ('property_location', models.CharField(max_length=100)),
                ('property_budget', models.CharField(max_length=100)),
            ],
        ),
    ]
