# Generated by Django 5.2.5 on 2025-10-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlist',
            new_name='wishlists',
        ),
    ]
