# Generated by Django 5.2.5 on 2025-10-15 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_app', '0001_initial'),
        ('user_app', '0003_rename_wishlist_wishlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlistss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('property_photo', models.ImageField(blank=True, null=True, upload_to='wishlist_photos/')),
                ('property_name', models.CharField(max_length=255)),
                ('property_location', models.CharField(max_length=255)),
                ('property_budget', models.CharField(max_length=100)),
                ('property_bedroom', models.CharField(max_length=100)),
                ('property_bathroom', models.CharField(max_length=100)),
                ('property_area', models.CharField(max_length=100)),
                ('property_floor', models.CharField(max_length=100)),
                ('property_parking', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_entries', to='builder_app.property_details')),
            ],
        ),
        migrations.DeleteModel(
            name='wishlists',
        ),
    ]
